### ISSUE TITLE
Cake 0.26 does not work with Cake.Bumpy

### ISSUE THREAD

**Issue by rw-nowakpiotr** [cake-contrib/Cake.Bumpy#11]
Error: The assembly 'Cake.Bumpy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by fwinkelbauer** [comment]
Thanks for bringing this up. Cake 0.26.0 introduced a [change](https://cakebuild.net/blog/2018/02/cake-v0.26.0-released) which breaks old addins.

Fixing this should not be hard. I won't be at home on the weekend, but you can expect an upgrade in 2-3 days!

Here a few workarounds you can use in the meantime:
- Use Bumpy via the console (that's what I do most of the time)
- Pin your version of Cake to a previous version (documented [here](https://cakebuild.net/docs/tutorials/pinning-cake-version))
- Call Bumpy via [StartProcess](https://cakebuild.net/dsl/process/)
