### ISSUE TITLE
Cake increment failing with Could not find part of the path

### ISSUE THREAD

**Issue by euronay** [cake-contrib/Cake.Bumpy#4]
I'm trying out Cake.Bumpy, and i started getting an issue a couple of days ago. My build script was running fine, but now if I run the build script in a clean directory, I get the following error in my logs:

```
========================================
Bump
========================================
Bumpy v0.6.0.0
Error: Invalid arguments. See 'bumpy help'.

An error occurred when executing task 'Bump'.
Error: One or more errors occurred.
        Bumpy: Process returned an error (exit code 1).
```

My cake script looks like this:
```c#
Task("Bump")
.Does(() => {
    var settings = new BumpySettings() {Profile = "library"};
    BumpyIncrement(4, settings);
});
```

I notice if I run my script with ```--verbosity=diagnostic```, the command executed is:

```
Executing: "C:/Dev/build-test-app/tools/bumpy/Bumpy/tools/Bumpy.exe" increment 4 -d "" -c "" -p library
```

**Comment by fwinkelbauer** [comment]
So that is whats happening if you are releasing an update without proper tests. Well I should have known better 😃 . Thanks so much for reporting/proposing a fix!

**Comment by fwinkelbauer** [comment]
The NuGet package should be ready in a few minutes. Thanks again!

Please let me know if there is anything I can help with concerning working with Bumpy

**Comment by gep13** [comment]
@euronay on a side note, sounds like you weren't pinning the version number of the Cake.Bumpy package, hence why it stopped working when it had been working.  We recommend pinning both the version of Cake that you are using, as well as the versions of the Addins/Modules/Tools that you are using.  There is more information about this here:

https://cakebuild.net/docs/tutorials/pinning-cake-version

**Comment by euronay** [comment]
Thanks, @fwinkelbauer. Appreciate the help!

@gep13, thanks for the heads up. I think I need that.

**Comment by gep13** [comment]
@euronay you are very welcome.  Feel free to jump into the Chat here: https://gitter.im/cake-build/cake if you have any other questions.
